specs/design-black-box.md, specs/design-white-box.md, specs/design.md
PR contains GitOps engine design proposal which references two documents:
- design-black-box.md - describes the POC approach
- design-white-box.md - an empty document for now. In next PR will move the content of https://docs.google.com/document/d/10OvgB9nMmleYPxPlLuXq6RNFodJSKZN7GUSNTyfwEhw/edit#
=> Add black box design proposal

README.md
Things I'd like to cover in here next (maybe separate PRs?):
=> add some explanation about what this project tries to do

README.md
Add a note about the license and code-of-conduct (using the one from CNCF) we use.
=> describe license and code-of-conduct

README.md
=> Point to #gitops on Kubernetes Slack for now

README.md
=> Add Ask-Us-Anything

README.md
Also link to PoC builds of Argo and Flux so people can take a look and try them out.
=> Clarify where we want contributions

README.md
=> document meeting times

README.md
=> Fix Slack invite: https://slack.k8s.io/

README.md
- Slack AMA is over
- Two WOUG sessions coming up
- Small link fix
=> Update events section

README.md, docs/faq.md
=> seed FAQ document with content from the Slack AMA session

pkg/engine/engine.go, pkg/utils/kube/cache/cluster.go, pkg/utils/kube/cache/cluster_test.go, pkg/utils/kube/cache/resource_test.go, pkg/utils/kube/cache/settings.go, pkg/utils/kube/cache/settings_test.go
=> fix: fix nil pointer dereference in cluster caching

Dockerfile, Makefile, agent/README.md, agent/main.go, agent/manifests/base/gitops-agent-deploy.yaml, agent/manifests/base/gitops-agent-sa.yaml, agent/manifests/base/kustomization.yaml, agent/manifests/cluster-install/gitops-agent-cluster-role-binding.yaml, agent/manifests/cluster-install/gitops-agent-cluster-role.yaml, agent/manifests/cluster-install/kustomization.yaml, agent/manifests/install-namespaced.yaml, agent/manifests/install.yaml, agent/manifests/namespace-install/gitops-agent-deployment-overlay.yaml, agent/manifests/namespace-install/gitops-agent-role-binding.yaml, agent/manifests/namespace-install/gitops-agent-role.yaml, agent/manifests/namespace-install/kustomization.yaml, go.mod, pkg/engine/engine.go, pkg/utils/diff/diff.go, pkg/utils/kube/sync/sync_context.go
PR implements GitOps Agent that leverages the GitOps Engine and provides access to many engine features via a simple CLI interface.
More details in readme file: https://github.com/alexmt/gitops-engine/blob/agent-example/agent/README.md
=> feat: implement gitops-agent

agent/main.go, pkg/sync/sync_context.go
PR enables resource pruning feature in gitops-agent
=> feat: support resource pruning in gitops-agent

pkg/diff/diff.go
PR removes the deprecated Diff field that is required to fix issue reported in https://github.com/argoproj/argo-cd/issues/3719
=> refactor: deprecates obsolete Diff field

pkg/cache/cluster.go, pkg/cache/settings.go
=> refactor: use UpdateSettingsFunc type

pkg/diff/diff.go, pkg/diff/diff_test.go, pkg/diff/testdata/deployment-config.json, pkg/diff/testdata/deployment-live.json, pkg/utils/json/json.go
First step to fix https://github.com/argoproj/argo-cd/issues/2865
=> fix: don't remove defaulted fields and rely only on three way diff merge during diffing

.github/dependabot.yml
https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/
=> chore: enable Dependabot v2

pkg/sync/sync_context.go
This is to fix: https://github.com/argoproj/argo-cd/issues/3915
=> fix: nil pointer while sync

pkg/sync/sync_context.go, pkg/sync/sync_context_test.go
PR improves the sync state messages that provide more visibility into why the syncing process takes time. 
After PR is merged the sync state will have a detailed message instead of `one or more tasks are running`. Examples:
* waiting for healthy state of /Pod/my-pod and 2 more resources
* waiting for completion of hook /Pod/my-pod
=> feat: improve sync operation messages

pkg/utils/kube/kube.go, pkg/utils/kube/kube_test.go
This is closer to what kubectl does.
=> fix: improve manifest parsing

pkg/utils/kube/kube.go
ctxCompleted is read and written from different goroutines, which is a data race.
This change also makes the sleep interruptible.
=> fix: data race on ctxCompleted

pkg/cache/cluster.go, pkg/utils/kube/kube.go
Updating function signature as discussed in https://github.com/argoproj/gitops-engine/pull/86.
=> refactor: improve func signature

pkg/cache/cluster.go
Please see individual commits.
=> Handlers cleanups

go.sum, pkg/cache/cluster.go, pkg/cache/references.go, pkg/cache/references_test.go, pkg/cache/resource.go
PR introduces dynamic discovery of StatefulSet to PVC ownership. Closes https://github.com/argoproj/argo-cd/issues/2924
=> feat: detect PVC StatefulSet ownership

pkg/diff/diff.go, pkg/health/testdata/statefulset.yaml, pkg/utils/json/json.go
Fixes https://github.com/argoproj/argo-cd/issues/4126
=> fix: volumeClaimTemplates are out of sync incorrectly

pkg/diff/diff.go
Closes https://github.com/argoproj/argo-cd/issues/4157
=> fix: exclude creationTimestamp from diffing

pkg/cache/cluster.go, pkg/sync/sync_context.go
Please see individual commits. I haven't fixed all the races here, but this is an improvement still.
=> fix: data race fixes and cleanups

agent/main.go, example.go, pkg/cache/cluster_test.go, pkg/diff/diff_test.go
- print using test logger
- print using fmt - println use is discouraged
=> refactor: cleanup printing and logging

pkg/cache/cluster.go
Improves changes of https://github.com/argoproj/gitops-engine/pull/133 (see https://github.com/argoproj/gitops-engine/pull/133#discussion_r478791575): ensure that response of every list request is processed completely when limiting semaphore is released.
=> refactor: ensure list semaphore is released after response is fully processed

OWNERS
Following the process, outlined here https://github.com/argoproj/argoproj/blob/master/community/membership.md#reviewer.
Sponsors: @alexmt @jessesuen.
=> Add myself as reviewer

pkg/sync/sync_context.go
- ref https://github.com/argoproj/gitops-engine/issues/181
=> Current time is not set in startedAt in NewSyncContext

pkg/utils/json/json.go
Signed-off-by: May Zhang <may_zhang@intuit.com>
=> fix: panic: interface conversion: interface {} is string

.github/workflows/ci.yaml, pkg/cache/cluster.go, pkg/cache/cluster_test.go, pkg/cache/mocks/ClusterCache.go, pkg/cache/predicates.go, pkg/cache/predicates_test.go
=> feat: add FindResources method that allows to find any resource in cache

pkg/sync/sync_context.go, pkg/utils/kube/ctl.go, pkg/utils/kube/kubetest/mock.go
Signed-off-by: Ishita Sequeira isequeir@redhat.com
issue: argoproj/argo-cd#[5368](https://github.com/argoproj/argo-cd/issues/5368)
Added cascade option to DeleteResource - argo-cd #5368
=> feat: added cascade option to DeleteResource - argo-cd #5368

pkg/sync/sync_context.go, pkg/sync/sync_context_test.go
PR allows controlling propagation policy during resource pruning.
=> feat: support resource prune propagation policy

pkg/sync/sync_context.go
Signed-off-by: May Zhang <may_zhang@intuit.com>
fixes: https://github.com/argoproj/argo-cd/issues/5736
=> fix: Dry run stuck on pre sync hook

agent/main.go
Signed-off-by: May Zhang <may_zhang@intuit.com>
=> fix: file extension comparisons are case sensitive

pkg/sync/sync_context.go
fixes https://github.com/argoproj/argo-cd/issues/5790
=> fix: sync option applyOutOfSync should not skip pruning

README.md
Signed-off-by: Shoubhik Bose <shbose@redhat.com>
=> docs: remove out-of-date sections

pkg/sync/sync_context.go, pkg/sync/sync_context_test.go, pkg/sync/sync_task.go
fixes https://github.com/argoproj/argo-cd/issues/5859
=> fix: applyOutOfSyncOnly should work with sync waves as well

pkg/cache/cluster.go
fixes https://github.com/argoproj/argo-cd/issues/5643
=> fix: register new CRD to apigroups

pkg/sync/sync_context.go
=> fix: applyoutofsync with dry-run

.github/workflows/ci.yaml, pkg/sync/sync_context.go
=> chore: switch CI to golangci/golangci-lint-action@v2

pkg/engine/engine.go
OnResourceUpdated() listener is trying to set `true` but nobody is receiving because the main goroutine has exited the for loop.
```
runtime.gopark(proc.go:337)
runtime.chansend(chan.go:257)
runtime.chansend1(chan.go:143)
github.com/argoproj/gitops-engine/pkg/engine.(*gitOpsEngine).Sync.func1(engine.go:101)    <--- this line blocks forever
github.com/argoproj/gitops-engine/pkg/cache.(*clusterCache).onNodeUpdated(cluster.go:896)
github.com/argoproj/gitops-engine/pkg/cache.(*clusterCache).processEvent(cluster.go:889)
github.com/argoproj/gitops-engine/pkg/cache.(*clusterCache).watchEvents.func1(cluster.go:528)
github.com/argoproj/gitops-engine/pkg/utils/kube.RetryUntilSucceed.func1(kube.go:377)
k8s.io/apimachinery/pkg/util/wait.PollImmediateUntil(wait.go:500) …
```
=> fix: deadlock in listener

pkg/health/health.go
PR implements two changes: 
* Adds `GetHealthCheckFunc` function that returns built-in health assessment function for a given resource (or nil )
* Prioritize Degraded health status over Missing. This change is required to "catch" degraded and out-of-sync Argo CD apps.
=> refactor: add an API that returns built-in health assessement function

pkg/cache/cluster.go, pkg/cache/cluster_test.go, pkg/cache/settings.go
Support managing cluster level resources in a namespaced mode
=> feat: support managing cluster resources in a namespaced mode

pkg/sync/sync_tasks.go, pkg/sync/sync_tasks_test.go
=> refactor: update resources install order according to helm implementation

pkg/utils/kube/resource_ops.go
Closes https://github.com/argoproj/argo-cd/issues/7088
=> fix: SyncOption Replace=True is broken

pkg/diff/diff.go, pkg/diff/diff_test.go
Fixes https://github.com/argoproj/argo-cd/issues/5584
=> fix: Address issue during diff when secret data is nil

pkg/utils/kube/kube.go
Part of https://github.com/argoproj/argo-cd/pull/7595
=> feat: add support split yaml that return actual yamls

pkg/health/health_hpa.go, pkg/health/testdata/hpa-v1-progressing.yaml
Closes https://github.com/argoproj/gitops-engine/issues/214
HPA health assessment function should check only condition type and status.
=> fix: health check for HPA doesn't catch all good states

pkg/sync/sync_context.go
Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>
=> fix: ensureCRDReady check did not work for v1 CRDs

.github/workflows/ci.yaml, Dockerfile
=> chore: Fix go version during ci lint

pkg/cache/cluster.go, pkg/cache/mocks/ClusterCache.go, pkg/utils/kube/ctl.go, pkg/utils/kube/kubetest/mock.go
Relates to https://github.com/argoproj/argo-cd/issues/9071
=> feat: add GvkParser in cluster cache

pkg/diff/diff.go, pkg/diff/diff_test.go, pkg/diff/testdata/smd-service-live.yaml
=> fix: structured-merge diff apply default values in live resource

pkg/health/health_daemonset.go, pkg/health/health_deployment.go, pkg/health/health_replicaset.go
then/than confusion isn't terribly uncommon. I've now added it to my list of things to flag...
=> spelling: less than

pkg/diff/diff.go
Fix: https://github.com/argoproj/argo-cd/issues/10438
=> fix: sort fields to correctly calculate diff in server-side apply

pkg/health/health_job.go, pkg/health/health_test.go, pkg/health/testdata/job-suspended.yaml
Signed-off-by: ashutosh16 <11219262+ashutosh16@users.noreply.github.com>
=> fix: add suspended condition

pkg/sync/common/types.go
Related https://github.com/argoproj/argo-cd/issues/7124
Related https://github.com/argoproj/argo-cd/pull/12448
Signed-off-by: Soumya Ghosh Dastidar <gdsoumya@gmail.com>
=> feat: add sync delete option

pkg/utils/kube/kube.go
Signed-off-by: ls0f <lovedboy.tk@qq.com>
=> manage clusters via proxy

pkg/diff/diff.go
Remove duplicate package imported twice.  It was added in https://github.com/argoproj/gitops-engine/commit/1c4ef336872ce4f30cf2b9134e7f8bcf57c3c813
=> improve: remove duplicate scheme package import

go.mod, go.sum
Adding updates from the last year, let's see if that fixed some bugs
=> chore(deps): Upgrade structured-merge-diff from v4.4.1 to v4.4.3

pkg/sync/sync_context.go
=> fix: Fix checking dryRun when using Server Side Apply (#699)

pkg/sync/sync_context_test.go
Adds unit test for https://github.com/argoproj/gitops-engine/commit/762f9b70f3056381aa782a4ea310a57919380d49
Covers the cases where if we are doing a dry run, we should never use server side apply.
=> chore: add unit test for ssa with dryRun

pkg/utils/kube/resource_ops.go
Cherry-pick https://github.com/argoproj/gitops-engine/pull/705 to 2.14
=> chore: Switch dry run applies to log with debug level

pkg/sync/sync_context.go, pkg/sync/sync_context_test.go
Related to https://github.com/argoproj/argo-cd/issues/21790
=> feat: Enable SkipDryRunOnMissingResource sync option on Application level

pkg/diff/diff.go, pkg/diff/diff_test.go, pkg/diff/testdata/data.go, pkg/diff/testdata/ssd-svc-label-live.yaml, pkg/diff/testdata/ssd-svc-no-label-config.yaml, pkg/diff/testdata/ssd-svc-no-label-predicted-live.json
cherry-pick of https://github.com/argoproj/gitops-engine/pull/722
=> fix: Server-Side diff removed fields missing in diff

pkg/utils/kube/resource_ops.go
cherry pick of https://github.com/argoproj/gitops-engine/pull/759 and https://github.com/argoproj/gitops-engine/pull/633 to close https://github.com/argoproj/gitops-engine/issues/623 on 3.1
=> fix: do not use --force with --dry-run

prepare.sh
Related to https://github.com/argoproj/argo-cd/issues/10774
Adds a script that will prepare this repo for migration to the main ArgoCD Repo 
The script will do the following : 
- Flattens the repository to a single directory
- removes any unwanted files
- creates a new branch to push the changes into
=> Adds a script to prepare repo for migration to main ArgoCD Repo

pkg/sync/sync_context_test.go, pkg/sync/sync_task.go
=> fix(sync): ApplyOutOfSyncOnly=true sync option is not honoured for cluster scoped resources (#765)
