specs/design-black-box.md
PR adds the target engine API.
The design is only inspired by PoC but represents that final state so pretty different from the implemented changes.
=> Add engine API to the black-box design

codecov.yml, pkg/utils/kube/cache/cluster.go
PR allows accessing most recent cluster cache synchronization error. Also adds comments to the top level cluster cache API.
=> feat: cluster cache should expose synchronization error

go.mod
=> chore: Speficy correct module dependency for kube-aggregator

pkg/sync/sync_context_test.go, pkg/utils/kube/kubetest/mock.go
https://github.com/argoproj/gitops-engine/issues/50
```
$ go test -race ./...
```
<details>
```
WARNING: DATA RACE
Write at 0x00c000818098 by goroutine 80:
github.com/argoproj/gitops-engine/pkg/utils/kube/kubetest.(*MockKubectlCmd).ApplyResource()
/Users/shunsuke-suzuki/repos/src/github.com/argoproj/gitops-engine/pkg/utils/kube/kubetest/mock.go:56 +0x56
github.com/argoproj/gitops-engine/pkg/sync.(*syncContext).applyObject()
/Users/shunsuke-suzuki/repos/src/github.com/argoproj/gitops-engine/pkg/sync/sync_context.go:572 +0x1a8
github.com/argoproj/gitops-engine/pkg/sync.(*syncContext).runTasks.func5.1()
/Users/shunsuke-suzuki/repos/src/github.com/argoproj/gitops-engine/pkg/sync/sync_context.go:783 +0x375
Previous write at 0x00c000818098 by goroutine 79: …
```
=> fix: Lock to write MockKubectlCmd.LastValidate to fix the race condition

pkg/cache/cluster.go
PR introduces an ability to limit the number of k8s list queries that helps to avoid memory spikes during controller initialization and resolves https://github.com/argoproj/argo-cd/issues/3241
=> feat: support limiting number of concurrent k8s list queries

agent/main.go, pkg/cache/cluster_test.go, pkg/diff/diff_test.go, pkg/utils/errors/errors.go
This is a part of Streamline exit codes of CLI (https://github.com/argoproj/argo-cd/issues/3592) issue on argo-cd.  
Continued from where @jannfis [left off](https://github.com/jannfis/argo-cd/commit/4b5574ed8509098476a4bf672a5c7e8020e82b6a)
Signed-off-by: darshanime <deathbullet@gmail.com>
=> refactor: add methods in errors package to quit with exit codes

README.md
This PR fixes markdown links in `README.md`.
=> fix: markdown links in README.md

pkg/utils/errors/errors.go
`CheckError` did not check if errors are `nil` before calling `Fatal`. 
Fixes regression introduced in 16575f18343d678f6beffde648bc6d54bc4b8a63
=> fix: Check for err != nil before Fatal

go.mod, go.sum, pkg/utils/json/json.go
gitops-engine does not use the `JSONMarshaler` type and pulling in a dependency for it is not great. Let's remove it please.
I'm trying to optimize the amount of stuff my project, that consumes the gitops-engine, needs to pull down and compile to work.
=> refactor: Drop github.com/grpc-ecosystem/grpc-gateway dependency

go.mod, go.sum, pkg/cache/cluster_test.go, pkg/diff/diff.go, pkg/diff/diff_test.go, pkg/health/health_test.go, pkg/utils/kube/convert_test.go, pkg/utils/kube/kube.go, pkg/utils/kube/kube_test.go, pkg/utils/testing/unstructured.go
Kubernetes community uses a permanent fork https://github.com/kubernetes-sigs/yaml
=> refactor: Replace ghodss/yaml with sigs.k8s.io/yaml

pkg/cache/cluster.go
Closes https://github.com/argoproj/argo-cd/issues/3670
The warning log level is misleading for this message. PR changes level to debug.
=> fix: change failed conversion log level to debug

go.mod, go.sum, pkg/diff/diff.go, pkg/diff/diff_test.go, pkg/diff/testdata/deployment-config.json, pkg/utils/json/json.go, pkg/utils/kube/convert.go, pkg/utils/kube/scheme/scheme.go
PR closes https://github.com/argoproj/argo-cd/issues/2865 . 
The only way to properly test built-in Kubernetes types without using K8S server is to execute server-side logic on the client. The PR implements server side k8s apply logic: uses built-in k8s type structure, apply default values and use strategic merge patch .
=> fix: diff should perform server side like apply during resource diffing

pkg/cache/cluster.go, pkg/cache/cluster_test.go, pkg/cache/resource.go
There is a request to display each age of Pods and resources in the ArgoCD issues.
To implement that request, I've added creation timestamp to Resource.
※Sorry if this PullRequest is annoying.
refs: https://github.com/argoproj/argo-cd/issues/3141
refs: https://github.com/argoproj/argo-cd/issues/2928
=> feat: add creation timestamp

pkg/diff/diff.go, pkg/diff/diff_test.go
The diffing should not fail if known k8s resource has invalid fields.
=> fix: diffing should not fail if known kubernetes resource has invalid fields

pkg/sync/sync_context.go, pkg/sync/sync_context_test.go, pkg/sync/sync_task.go, pkg/sync/sync_task_test.go
Closes https://github.com/argoproj/argo-cd/issues/2737
PR changes hook deletion logic so that hooks are deleted after sync phase/wave is completed.
=> fix: sync hooks should be deleted after sync phase/wave completion

agent/main.go, pkg/utils/kube/kube.go
apimachinery provides library code to parse multi document YAML, there is no need to resort to regexes. Regexes also don't take into account the document start/end marker that might be somewhere in a string in the middle of a YAML document.
=> fix: use streaming YAML decoder from Kubernetes

pkg/cache/cluster.go, pkg/cache/settings.go, pkg/cache/settings_test.go
PR adds the ability to override cluster cache re-sync timeout.
=> feat: support configuring cluster cache re-sync timeout

pkg/cache/cluster.go, pkg/cache/settings.go
`rest.Config` has `RateLimiter` that should be used for rate limiting. It's not very good to have global state in a library too.
=> refactor: remove global semaphore

README.md, docs/faq.md
It's been a while since we wrote most of the docs for the GitOps Engine. In the meantime the Flux project has announced the plans to build Flux v2 on top of the [GitOps Toolkit](https://toolkit.fluxcd.io/). This PR aims to update the docs to reflect this.
For everyone hasn't followed the news closely: This was discussed between project leads of both projects and we consider the time of collaboration as very fruitful: both Argo and Flux developed a new vision on this quest.
Right now this is a draft PR still, some other bits might need updating but I'd defer the decision to maintainers of the GitOps Engine.
What I did in the PR already:
- update main README
- add some more backstory in the FAQ
What I can see as TODO (potentially part of subsequent PRs though):
- update diagram in main …
=> docs: Update notes on Argo+Flux collaboration

Makefile, pkg/cache/cluster.go, pkg/cache/cluster_test.go, pkg/cache/settings_test.go
We've started seeing cache inconsistency issues recently on both v1.6.0 and v1.7.0 instances. The issue is not intermittent and does not have clear steps to reproduce. I think there are two reasons:
* Argo CD should not rely on 100% watch API correctness. Due to possible racing conditions, some events might be handled in the wrong order or missed. 
* we don't handle all Watch API edge cases and because Argo CD should not rely on 100% watch API correctness. 
PR fixes both issues:
* Introduces periodical ( every 10 mins ) re-synchronization of each monitored API
* Leverages RetryWatcher that simplifies watch API usage and handles API edge cases.
=> fix: leverage RetryWatcher to watch cluster events and introduce periodical K8S API state resynchronization

pkg/engine/engine.go
It's the standard pattern to return `ctx.Err()` when context is done.
=> refactor: Return error from context

pkg/cache/cluster.go, pkg/cache/cluster_test.go
Signed-off-by: John Pitman <jpitman@redhat.com>
Related to https://github.com/argoproj/argo-cd/issues/4329
Return an error from `clusterCache.GetManagedLiveObjs` if we find a target object in a namespace that is not managed by the cluster.
=> fix: check resource namespaces are managed

pkg/cache/cluster.go, pkg/cache/cluster_test.go
The controller cache incorrectly notifies consumer every 10 minutes when re-syncs the K8S API. The PR fixes that issue
=> fix: avoid memory and events spike after forcefully refreshing api cache

pkg/health/health.go, pkg/health/health_test.go
Signed-off-by: Keith Chong <kykchong@redhat.com>
This fix is for ArgoCD issue: https://github.com/argoproj/argo-cd/issues/3781
Remove health assessment check for applications
=> fix: Child apps should not affect parent app's health by default

pkg/utils/kube/kube.go, pkg/utils/kube/kube_test.go
Update NewKubeConfig to copy the TLSClientConfig.ServerName to the
TLSServerName field of the cluster. This will allow for connecting
to an API server behind a load balancer when the load balancer DNS
name or IP does not match the API server TLS certificate.
=> Set TLSServerName in NewKubeConfig

pkg/diff/diff.go, pkg/diff/diff_test.go
There are a couple of spots in `diff.go` that are unmarshalling JSON resource data into k8s structs, but in doing so they are silently tossing (invalid) JSON fields that are not present in that struct. In general, this is due to the use of `json.Unmarshal(...)` (whose default implementation silently ignores extra fields) in conjunction with k8s structs that do not contain those extra fields.
The fix is:
- Use `decoder := json.NewDecoder(strings.NewReader(string(data)))` and `decoder.DisallowUnknownFields()` to detect unknown fields when `remarshall`ing
- When `applyPatch`ing against a Kubernetes resource, indirectly apply the result of the scheme default functions to the target JSON, rather than directly marshalling the scheme function results to the k8s resource (which would cause those …
=> fix: Detect unknown fields in invalid specs as OutOfSync 

pkg/sync/sync_context.go, pkg/sync/sync_task.go, pkg/sync/sync_tasks.go, pkg/sync/sync_tasks_test.go
PR changes sync tasks sorting so that CRD and Namespace always created before matching CRs or objects in the same namespace.
Closes https://github.com/argoproj/argo-cd/issues/4354
=> feat: Namespace/CRD creation should happen before PreSync phase

pkg/utils/kube/ctl.go, pkg/utils/kube/kubetest/mock.go
I will need to start using PatchResource with the `status` subresources in order to fix https://github.com/argoproj/argo-cd/issues/4670. This change updates method signature to carry forward the subresources string array.
=> refactor: allow PatchResource to accept subresource

pkg/diff/diff.go, pkg/sync/common/types.go, pkg/sync/sync_context.go, pkg/sync/sync_context_test.go, pkg/utils/kube/kube.go
This is groundwork for fixing https://github.com/argoproj/argo-cd/issues/4669. It introduces a SyncWaveHook callback function, which is invoked after successfully applying each sync wave. Argo CD will leverage this by sleeping for a few seconds between each wave.
Also this fixes some logging issues after switching to the new logr.
=> feat: introduce SyncWaveHook callbacks which are invoked after applying each sync wave

pkg/sync/sync_context.go, pkg/sync/sync_context_test.go
This is a follow up to https://github.com/argoproj/gitops-engine/pull/180.
When resuming a sync operation, we need startTime to be stable from previous reconciliation, because startTime is used in sync hooks which use generateName(). Without this fix, we get into a continuous loop where we create infinite number of hooks when they use generateName.
=> fix: WithInitialState should require start time to support generateName hooks properly

pkg/sync/common/types.go, pkg/sync/sync_context.go, pkg/sync/sync_context_test.go
fixes: #5080.
If sync option has `PruneLast=true`, or individual resource has annotation `argocd.argoproj.io/sync-options: PruneLast=true`, these prune tasks get assigned with a new sync wave.
the new sync wave is the last sync wave of non-prune tasks which is in sync phase + 1, so that these resources will be pruned after all sync phase resources are synced and healthy.
=> feat: prune last

pkg/cache/cluster.go, pkg/cache/settings.go, pkg/cache/settings_test.go
The fix is straightforward, as far as these things go: 
- Introduce a new lock, `clusterCacheSync.lock` which is only used for accessing the `syncStatus` fields of the cluster cache.
- Move fields into a `clusterCacheSync` struct which is managed by that lock
- This new lock is much cheaper to acquire than the cluster lock, since it does not block on the same heavyweight operations which use the cluster lock (with the one pre-existing exception of `EnsureSynced`'s resync operation)
- Add lock acquisition to code that uses `syncStatus`
- Add comment describing rules for acquiring `syncStatus` so that we don't deadlock.
**Parent issue**:
https://github.com/argoproj/argo-cd/issues/4627
=> fix: Data race between gitops-engine's pkg/cache/cluster.go and itself, on Argo CD startup (#4627)

.gitignore, pkg/sync/sync_context.go, pkg/sync/sync_context_test.go
issue: https://github.com/argoproj/argo-cd/issues/3877
argo-cd PR: https://github.com/argoproj/argo-cd/pull/5347
This feature applies only out-of-sync resources when `ApplyOutOfSync=true` option is provided by user. 
Scenario: For an application with 10 deployments and 1 svc, deleting svc and syncing entire application (performing same action)
With `ApplyOutOfSync=true` enabled
```
INFO[0040] sync/terminate complete              application=guestbook duration=507.61639ms syncId=00001-NPWVT
```
Without `ApplyOutOfSync=true` enabled
```
INFO[0114] sync/terminate complete              application=guestbook duration=1.983608856s syncId=00002-orWNj
```
=> feat: selective sync

pkg/sync/sync_context.go, pkg/sync/sync_task.go, pkg/sync/sync_tasks.go, pkg/sync/sync_tasks_test.go
PR fixes issues reproduced in Argo CD (https://github.com/argoproj/argo-cd/issues/5522) and Gitlab agent ([#96](https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent/-/issues/96)) .
During the syncing process, the engine should sync namespaces and CRD before dependent resources ( regardless of sync waves/sync hooks annotations ). This behavior was supposed to be implemented by https://github.com/argoproj/gitops-engine/pull/159 however it was done with a bug: current implementation would work only if the sorting function being executed against all possible sync tasks pair which is not true.
PR rollback changes in sorting function and implements the Namespace/CRD handling in a separate function.
=> fix: sync should apply Namespaces and CRDs before resources that depend on them

pkg/health/health_hpa.go, pkg/health/health_test.go, pkg/health/testdata/hpa-v1-healthy-toofew.yaml
In the case that you have a HPA with a minimum or maximum replica count set, and the metrics would indicate a need to scale beyond those, this is still an expected and healthy state.
I've got a Deployment & HPA, which doesn't have much load right now, but still has a minimum replicas set to 2 (for HA). This means Argo CD is currently constantly showing it as Progressing, which isn't correct.
Here I'm trying to add the additional healthy states I see.
I wonder though, is checking conditions correct, or should this be checking if the `Status` of the condition is True?
(e.g. is healthy == AbleToScale.Status == True && ScalingActive.Status == True)
=> fix: Add additional healthy states for HPA

go.sum, pkg/sync/common/types.go, pkg/sync/sync_context.go, pkg/sync/sync_context_test.go, pkg/utils/kube/ctl.go, pkg/utils/kube/kubetest/mock.go
PR introduces support for `Replace=true` sync option that enables use of `kubectl replace` instead of `kubectl apply` .
=> feat: support 'Replace=true' sync option

pkg/sync/sync_context.go, pkg/utils/kube/ctl.go, pkg/utils/kube/kubetest/mock.go
Addresses issue reported in https://github.com/argoproj/argo-cd/issues/820 for CRDs. The sync should attempt to just update CRD spec if `Replace=true` sync option is specified. The update won't attempt to recreate CRD so it is safe and it is not trying to set `last-applied-configuration` annotation .
=> feat: support replace strategy for CRD

go.mod, internal/kubernetes_vendor/pkg/api/v1/endpoints/util.go, internal/kubernetes_vendor/pkg/util/hash/hash.go, pkg/diff/diff.go, pkg/health/health_pod.go
Updates #56.
This is a reduced version of https://github.com/argoproj/gitops-engine/pull/205 that does not remove conversion.
=> refactor: reduce usage of k8s.io/kubernetes packages take 2

pkg/cache/cluster_test.go
`FakeDynamicClient` returns typed lists (not unstructured lists) since Kubernetes 1.20. The type cast now handles that. It's a bug I introduced in #195, sorry about that.
Fixes #254.
=> fix: missing resource version in tests

pkg/engine/engine.go, pkg/sync/sync_context.go, pkg/sync/sync_context_test.go, pkg/utils/kube/ctl.go, pkg/utils/kube/kubetest/mock.go, pkg/utils/kube/resource_ops.go
Changes implemented in PR ensures that `sync_context` uses one instance of `cmdutil.Factory` from `github.com/kubernetes/kubectl` package to perform `kubectl apply/create/replace` operations. This significantly improves syncing performance and reduces memory usage. 
Tested with a sample app that consists of ~40 Config Maps. Synchronization is ~100 times faster (~0.2s instead of ~30s) and ~100 less memory usage ( ~16 mb instead of 1.3gb ).
=> refactor: cache cmdutil.Factory to improve synchronization performance

pkg/cache/cluster.go, pkg/cache/cluster_test.go
PR allows getting a list of cluster API groups using the `GetClusterInfo` method.
=> feat: expose APIGroups in GetClusterInfo

pkg/utils/kube/ctl.go, pkg/utils/kube/resource_ops.go
PR is an attempt to fix https://github.com/argoproj/gitops-engine/issues/286 . After merging the https://github.com/argoproj/gitops-engine/pull/281 some sync operations intermittently fail with  `no matches for kind <Kind> in group <Group>` error. This error is returned by `RESTMapper` object that is created by `openapi.Resources` . The https://github.com/argoproj/gitops-engine/pull/281 introduced caching of `openapi.Resources` object that is probably the root cause of the issue. 
I've reverted that `openapi.Resources` caching and discovered that it does not affect performance. It is enough to cache just that `cmdutil.Factory` . Hence removing `openapi.Resources` caching. Hopefully, it will resolve the …
=> refactor: stop caching OpenAPISchema since it is cached by cmdutil.Factory

pkg/cache/cluster.go, pkg/engine/engine.go, pkg/sync/sync_context.go, pkg/utils/kube/ctl.go, pkg/utils/kube/kubetest/mock.go, pkg/utils/kube/resource_ops.go
Keep open api schema in cluster live state cache to avoid reloading it every sync
=> refactor: using open api schema in cluster live state cache

pkg/health/health_argo.go, pkg/health/health_test.go
Resolves https://github.com/argoproj/argo-cd/issues/6541
Workflows that have an empty `status.phase` have yet to be observed by the workflow controller, and should be considered Progressing, not Healthy.
Signed-off-by: Jesse Suen <jessesuen@gmail.com>
=> fix: workflows with empty status.phase should be considered Progressing

pkg/sync/sync_context.go, pkg/utils/kube/kubetest/mock.go, pkg/utils/kube/resource_ops.go
Closes https://github.com/argoproj/argo-cd/issues/6578
PR changes implementation of  'ResourceOperations.CreateResource' to use kubectl package so it won't fail incorrectly during dry run.
=> fix: 'ResourceOperations.CreateResource' should use 'kubectl' package to properly execute create operation

pkg/health/health_hpa.go
fixes https://github.com/argoproj/argo-cd/issues/7561
=> fix: add ScaleDownLimit as health state for HPA

pkg/cache/cluster.go, pkg/cache/settings.go, pkg/cache/settings_test.go
When troubleshooting a users performance problem, I found many tunable were not configurable and hard wired into the gitops engine. So I made the following changes:
* Adds the ability to disable the 24h (12h in Argo CD) cluster resync period by setting the value to 0. This will result in the gitops-engine relying on the resource watch resync to correctly resync the cache.
* Also makes the resource watch resync period configurable (from the default of 10m)
* Watch resource resync can also be disabled by setting a value to 0
Signed-off-by: Jesse Suen <jesse@akuity.io>
=> feat: configurable watch resync timeout. ability to disable cluster resync

pkg/diff/diff.go, pkg/diff/diff_test.go
=> fix: removeNamespaceAnnotation should not panic if annotation has unexpected value

pkg/diff/diff.go, pkg/diff/testdata/endpoints-config.json, pkg/diff/testdata/endpoints-live.json
Signed-off-by: Roman Rudenko <3kmnazapad@gmail.com>
Fixes https://github.com/argoproj/argo-cd/issues/6300
by adding default protocol to subset of ports if it is not defined before sorting
=> fix: add default protocol to subset of ports if it is empty

pkg/cache/cluster.go, pkg/cache/settings.go
Signed-off-by: Ben Ye <ben.ye@bytedance.com>
This pr exposes the sync retry duration when there is a sync error. The default is only 10s and for some large clusters, several unknown state apps will trigger a lot of full cluster sync every 10s.
Making it configurable improves the performance in the case above. Once this pr gets accepted then I will update the ArgoCD side as well.
=> feat: expose cluster sync retry timeout

pkg/cache/cluster.go, pkg/cache/settings.go
Sometimes, transient errors can occur when listing large sets of resources. This is especially true for far edge clusters with high latency and/or low bandwidth connections.
This adds configurable retry capabilities to the cluster cache sync when listing resources by providing the `SetRetryOptions(maxRetries int32, useBackoff bool, retryFunc ListRetryFunc)` method. 
Signed-off-by: jannfis <jann@mistrust.net>
=> feat: Support for retries when building up cluster cache

go.mod
This is to match with Argo CD https://github.com/argoproj/argo-cd/blob/master/go.mod#L3.
Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>
=> chore: Bump Go to 1.17

pkg/sync/sync_tasks.go, pkg/sync/sync_tasks_test.go
Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>
=> fix: Add missing IngressClass in kind order when syncing tasks

pkg/health/health.go, pkg/health/health_daemonset.go, pkg/health/health_deployment.go, pkg/health/health_replicaset.go, pkg/health/health_statefulset.go, pkg/health/testdata/deployment-degraded.yaml, pkg/health/testdata/deployment-progressing.yaml, pkg/health/testdata/deployment-suspended.yaml, pkg/health/testdata/ingress-nonemptylist.yaml, pkg/health/testdata/ingress-unassigned.yaml, pkg/health/testdata/ingress.yaml, pkg/utils/kube/ctl_test.go, pkg/utils/kube/testdata/nginx.yaml
This PR removed all extensions APIs besides Ingress because extensions Ingress is still available in 1.21. We will remove it later when 1.21 has reached to EOL.
Reference: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>
=> chore: Remove support for deprecated extensions APIs

pkg/utils/kube/ctl.go, pkg/utils/kube/resource_ops.go
This allows to set Kubernetes client QPS and burst rates for the resource ops client, according to the configuration of the client.
Needs a very small change in Argo CD as well, which will be submitted separately.
Supersedes #349 
Signed-off-by: jannfis <jann@mistrust.net>
=> fix: Set QPS and burst rate for resource ops client

pkg/sync/common/types.go, pkg/sync/sync_context.go, pkg/sync/sync_context_test.go, pkg/utils/kube/kubetest/mock.go, pkg/utils/kube/resource_ops.go
See https://github.com/argoproj/argo-cd/issues/2267
=> Server-side apply

pkg/cache/cluster_test.go, pkg/utils/kube/kubetest/mock.go
Argo CD currently has an e2e test which verifies that, if a resource version conversion isn't possible locally, we'll fall back to server-side conversion.
That test is difficult to maintain because it relies on having a CRD which is 1) not convertible locally and 2) _is_ convertible server-side for all supported k8s versions and whatever version of k8s the developer is running locally.
I want to [remove that e2e test](https://github.com/argoproj/argo-cd/issues/9046) because the maintenance overhead is excessive.
This PR checks for the behavior that the e2e test checks - do we fall back to server-side conversion if local conversion fails.
=> chore: test resource conversion

pkg/health/health_hpa.go, pkg/health/health_test.go, pkg/health/testdata/hpa-v2-degraded.yaml, pkg/health/testdata/hpa-v2-healthy.yaml, pkg/health/testdata/hpa-v2-progressing.yaml
Currently health check for HorizontalPodAutoscaler is limited to v1, v2beta1 and v2beta2. 
This MR adds support for v2 which is the default HPA API version on Kubernetes 1.23+
Without this MR, ArgoCD will fail to sync any applications that use HPA in Kubernetes 1.23+ clusters.
=> feat: Add support for HPA v2 (autoscaling/v2)

pkg/cache/cluster.go
Fixes argoproj/gitops-engine#425
Change wrong log level from `Error` to `Warning`.
=> fix: Change wrong log level in cluster.go openAPISchema, gvkParser

pkg/sync/sync_context.go
The signature for the `resourcesFilter` function in the sync context is
```go
resourcesFilter        func(key kube.ResourceKey, target *unstructured.Unstructured, live *unstructured.Unstructured) bool
```
but it's called with `live` and `target` exchanged.
This is a prerequisite for fixing https://github.com/argoproj/argo-cd/issues/8683
Signed-off-by: jannfis <jann@mistrust.net>
=> fix: Fix argument order in resource filter

pkg/sync/sync_context.go, pkg/sync/sync_context_test.go
https://github.com/argoproj/argo-cd/issues/7799
=> feat: Ability to create custom labels for namespaces created with syncOptions CreateNamespace

pkg/sync/sync_context.go, pkg/sync/sync_context_test.go
=> fix: retry on unauthorized error when retrieving resources by gvk

agent/README.md, agent/main.go, pkg/cache/cluster.go, pkg/utils/text/text.go
Using env variables to enable profiling mode, the agent can be started with the following envs:
```bash
export GITOPS_ENGINE_PROFILE=web
export GITOPS_ENGINE_PROFILE_HOST=127.0.0.1
export GITOPS_ENGINE_PROFILE_PORT=6060
```
And then you can open profile in the browser(or using [pprof](https://github.com/google/pprof) cmd to generate diagrams):
- http://127.0.0.1:6060/debug/pprof/goroutine?debug=2
- http://127.0.0.1:6060/debug/pprof/mutex?debug=2
logr will panic when format with none string params, error meesage:
```
key is not a string: "error creating gvk parser: duplicate entry for /v1, Kind=WatchEvent"
```
=> feat: add profile feature for agent, and fix logr's panic

pkg/sync/sync_context.go, pkg/sync/sync_context_test.go
Rename `WithNamespaceCreation` to `WithNamespaceModifier`, since this
method is also used for modifying existing namespaces. This method
takes a single argument for the actual updating, and unless this method
gets invoked by its caller no updating will take place (fulfilling what
the `createNamespace` argument used to do).
Within `autoCreateNamespace`, everywhere where we previously added tasks
we'll now need to check whether the namespace should be created (or
modified), which is now delegated to the `appendNsTask` and
`appendFailedNsTask` methods.
=> Update namespace v2

pkg/sync/sync_context.go, pkg/sync/sync_context_test.go
When enabled, managed namespace shouldn't mutate the live state directly.
=> fix: managed namespaces should not mutate the live state

pkg/cache/cluster.go
Closes https://github.com/argoproj/argo-cd/issues/11458
PR fixes deadlock in cluster caching code that causes app controller to stop working suddenly:
Deadlock is triggered by cluster re-syncing and happening because code it trying to acquire mutex and semaphore at the same time:
https://github.com/argoproj/gitops-engine/blob/ed70eac8b7bd6b2f276502398fdbccccab5d189a/pkg/cache/cluster.go#L543
```golang
// listResources acquires semaphore and releases when method exits
resourceVersion, err = c.listResources(ctx, resClient, func(listPager *pager.ListPager) error {
...
// runSynced acquires mutex so listResources cannot exit until c.lock is acquired
return runSynced(&c.lock, func() error {
c.replaceResourceCache(api.GroupKind, items, ns)
return nil
})
})
})
```
during cluster resyncing method …
=> fix: avoid acquiring lock on mutex and semaphore at the same time to prevent deadlock

pkg/sync/sync_context.go, pkg/sync/sync_context_test.go
When doing `kubectl replace`, namespaces should not be affected. Fixes argoproj/argo-cd#12810 and argoproj/argo-cd#12539.
=> fix: do not replace namespaces

pkg/sync/common/types.go
Required for https://github.com/argoproj/argo-cd/pull/14624/files
=> feat: Apply out of sync option only

pkg/cache/cluster.go, pkg/cache/settings.go
This PR implements this [proposal](https://github.com/argoproj/argo-cd/blob/master/docs/proposals/respect-rbac-for-resource-exclusions.md). PR enables gitops engine to automatically stop watching for resources that it does not have permission to access without having to manually set resource exclusions.
=> feat: auto respect rbac for discovery/sync

pkg/cache/cluster.go
Right now we only pass this up to the caller to log. That has two downsides:
1) The caller may not log it (there's at least one such case in Argo CD)
2) The caller may log it _too often_, producing duplicate log lines and making it difficult to determine exactly how many clusters are "sick" - for example, Argo CD logs this error for every single Application deployed to the sick cluster
=> chore: log cluster sync error

pkg/cache/cluster.go
Partially addresses https://github.com/argoproj/argo-cd/issues/15850.
The lock we were acquiring in GetAPIResources() was unnecessary and caused Argo CD app reconciliation to spend extra time waiting to get API resource information.
=> fix: remove lock acquisition in ClusterCache.GetAPIResources()

pkg/sync/sync_context.go, pkg/sync/sync_context_test.go
Closes: https://github.com/argoproj/argo-cd/issues/16177
=> fix(server): use server side dry run in case if it is server side apply

pkg/sync/sync_context.go
Fixes for https://github.com/argoproj/gitops-engine/pull/547
Closes: https://github.com/argoproj/argo-cd/issues/16177
=> feat: retry with client side dry run if server one was failed

pkg/diff/diff.go, pkg/utils/kube/resource_ops.go
fix: https://github.com/argoproj/argo-cd/issues/16840
=> fix: address kubectl auth reconcile during server-side diff

pkg/sync/sync_context.go, pkg/sync/sync_context_test.go, pkg/utils/kube/resource_ops.go
When server side apply is set to true, dry run is run in server mode. Dry run in server mode will fail if the target namespace is missing. So in cases where the sync option `CreateNamespace` is set to true, the dry run fails in server mode, and then attempts to re-run in client mode as a fallback mechanism. But the server side apply is still set. This is not a supported configuration in `kubectl` when `--dry-run` is set to client, `--server-side` flag is not supported causing that to fail as well with the below error message
```
error: --dry-run=client doesn't work with --server-side (did you mean --dry-run=server instead?)
``` 
Due to this behaviour, when both `CreateNamespace=true` and `ServerSideApply=true` sync options are used, then the app sync fails while trying to validate the …
=> fix(server): Dry run always in client mode just for yaml manifest validation even with server side apply

pkg/sync/sync_context.go, pkg/sync/sync_context_test.go, pkg/sync/sync_task.go
This PR implements https://github.com/argoproj/argo-cd/issues/15074 enhancement to prune resources in reverse order of sync waves. 
Changes:
- Adds reordering logic which swaps waves between resources marked for pruning such that resources with high syncwave value is deleted first before resources with lower syncwave value.
- Adds wait till the pruned resource is actually cleaned up from the cluster before moving to next wave.
- Updates prune last logic to  also consider prune tasks to determine last wave.
Related: https://github.com/argoproj/argo-cd/issues/12376
=> feat: Prune resources in reverse of sync wave order

pkg/cache/cluster.go
CRD updates are memory/CPU expensive. If CRDs are changing often, that can cause performance issues. Log changes to help users diagnose performance issues.
=> chore: more logging for CRD updates

pkg/utils/io/io.go, pkg/utils/kube/ctl.go, pkg/utils/kube/resource_ops.go
Fixes #568 
See [parent issue](https://github.com/argoproj/gitops-engine/issues/568) for details of the problem
This PR:
- `ctl.go`: Adds a call to `DeleteFile` to handle the (rare) case where `WriteKubeConfig` fails.
- `resource_ops.go`: Moves `defer io.DeleteFile(...)` call to handle the (rare) case where Write or Close fail.
Admittedly, these are likely to be rare: it's unlikely that writing to a file would fail, when that file was already successfully created earlier in the function.
=> fix: temporary files written to '/dev/shm' not cleaned up (#568)

pkg/diff/diff.go
fix https://github.com/argoproj/argo-cd/issues/18020
=> fix: handle nil ParseableType from GVKParser

pkg/cache/references.go, pkg/cache/references_test.go
We have 2 pvc in namespace, one with name `emqx-data-sw-broker-0` for statefulset `sw-broker` and other one is `emqx-data-sw-broker-internal-0` for statefulset `sw-broker-internal` and both have same template name `emqx-data`. since `emqx-data-sw-broker-internal-0` contains prefix `emqx-data-sw-broker-`, it consider it as part of sw-broker statefulset which is not right. fixing condition to check if it contains number at the end of prefix
=> Update condition to select right pvc as child for statefulset

go.mod
Followup for https://github.com/argoproj/gitops-engine/pull/566
PR adds replace for k8s.io/endpointslice to fix `go list -m -json all` command
=> fix: replace k8s.io/endpointslice version

pkg/cache/cluster.go
The log.Info function doesn't understand format directives, so use key/value to print error message.
Related PR which caused the error to be hidden: #430 
I'm not sure if this should stay at Info level or if it was correct previously at error level because this is a real issue.  The failed gvkParser seems to be the cause of inaccurate diffs: [#18213](https://github.com/argoproj/argo-cd/issues/18213)
=> fix: printing gvkparser error message

pkg/cache/cluster.go, pkg/cache/cluster_test.go, pkg/cache/resource_test.go
- The callback on listResources must not obtain locks from other callers.
Caused by https://github.com/argoproj/gitops-engine/pull/532
Fixes https://github.com/argoproj/argo-cd/issues/18467
Fixes https://github.com/argoproj/argo-cd/issues/18902
Fixes https://github.com/argoproj/argo-cd/issues/16950
=> fix: deadlock on start missing watches

pkg/sync/reconcile.go, pkg/sync/reconcile_test.go
1. ~namespacedResources is accessed by multiple goroutines simultaneously
and therefore must be guarded by a mutex. Because this field is read
significantly more often than it's written, use an RWMutex.~ Removed this from this PR, as it might not be adequate in its current form to avoid deadlocks.
2. When Reconcile performs its logic to compare the desired state (target
objects) against the actual state (live objects), it looks up each live
object based on a key comprised of data from the target object: API
group, API kind, namespace, and name. While group, kind, and name will
always be accurate, there is a chance that the value for namespace is
not. If a cluster-scoped target object has a namespace (because it
incorrectly has a namespace from its source) or the namespace parameter
passed …
=> fix(clusterCache): don't miss finding live obj if obj is cluster-scoped and namespacedResources is in transition

pkg/sync/reconcile.go, pkg/sync/reconcile_test.go
* sync.Reconcile: guard against incomplete discovery
When Reconcile performs its logic to compare the desired state (target objects) against the actual state (live objects), it looks up each live object based on a key comprised of data from the target object: API group, API kind, namespace, and name. While group, kind, and name will always be accurate, there is a chance that the value for namespace is not. If a cluster-scoped target object has a namespace (because it incorrectly has a namespace from its source) or the namespace parameter passed into the Reconcile method has a non-empty value (indicating a default value to use on namespace-scoped objects that don't have it set in the source), AND the resInfo ResourceInfoProvider has incomplete or missing API discovery data, the call to …
=> fix(clusterCache): don't miss finding live obj if obj is cluster-scoped and namespacedResources is in transition (2.11)

pkg/sync/reconcile.go, pkg/sync/reconcile_test.go
* sync.Reconcile: guard against incomplete discovery
When Reconcile performs its logic to compare the desired state (target objects) against the actual state (live objects), it looks up each live object based on a key comprised of data from the target object: API group, API kind, namespace, and name. While group, kind, and name will always be accurate, there is a chance that the value for namespace is not. If a cluster-scoped target object has a namespace (because it incorrectly has a namespace from its source) or the namespace parameter passed into the Reconcile method has a non-empty value (indicating a default value to use on namespace-scoped objects that don't have it set in the source), AND the resInfo ResourceInfoProvider has incomplete or missing API discovery data, the call to …
=> fix(clusterCache): don't miss finding live obj if obj is cluster-scoped and namespacedResources is in transition (2.10)

pkg/sync/reconcile.go, pkg/sync/reconcile_test.go
* sync.Reconcile: guard against incomplete discovery
When Reconcile performs its logic to compare the desired state (target objects) against the actual state (live objects), it looks up each live object based on a key comprised of data from the target object: API group, API kind, namespace, and name. While group, kind, and name will always be accurate, there is a chance that the value for namespace is not. If a cluster-scoped target object has a namespace (because it incorrectly has a namespace from its source) or the namespace parameter passed into the Reconcile method has a non-empty value (indicating a default value to use on namespace-scoped objects that don't have it set in the source), AND the resInfo ResourceInfoProvider has incomplete or missing API discovery data, the call to …
=> fix(clusterCache): don't miss finding live obj if obj is cluster-scoped and namespacedResources is in transition (2.9)

pkg/utils/kube/resource_ops.go
This change is for propogating impersonation related configurations to the `kubeconfig` used for executing the `kubectl` command.
=> Added support for impersonation in the kubectl

pkg/cache/references.go
Sitting at the airport with nothing better to do than micro-optimize stuff.
```
before: Benchmark_resolveResourceReferences-16           4676506               252.4 ns/op            82 B/op          3 allocs/op
after: Benchmark_resolveResourceReferences-16            8308146               143.6 ns/op            82 B/op          3 allocs/op
```
I didn't commit the benchmark code, because it's trivial and shouldn't be needed in the future. Here it is for inspection:
```go
func Benchmark_resolveResourceReferences(b *testing.B) {
manifest := []byte(`
apiVersion: extensions/v1beta2
kind: Deployment
metadata:
name: nginx-deployment
labels:
foo: bar
uid: '123'
ownerReferences:
- apiVersion: apps/v1
kind: StatefulSet
name: sw-broker
uid: '456'
`)
obj := unstructured.Unstructured{}
err := …
```
=> chore: speed up resolveResourceReferences

pkg/diff/diff.go
As far as I can tell, the only purpose these lines serve is to confirm that `predictedLiveBytes` is valid JSON. But at this point in the code, I don't think we have any reason to believe that the JSON is _not_ valid. We're relying on solid libraries to produce that JSON. Even if the JSON were somehow invalid, I'm not sure there's any value in validating it here versus where it's eventually used.
Here's the benchmark output:
```
before: Benchmark_threeWayMergePatch-16            21823             53131 ns/op           41018 B/op        861 allocs/op
after:  Benchmark_threeWayMergePatch-16            22926             52559 ns/op           39072 B/op        810 allocs/op
```
It's a small but not insignificant memory and compute win. I think the benefits increase as the JSON size increases. …
=> chore: avoid unnecessary json unmarshal

pkg/diff/diff.go, pkg/diff/diff_test.go
We have a utility function `stripTypeInformation` that json marshals and then unmarshals an unstructured in order to remove type information before diffing.
The only caller of `stripTypeInformation` immediately JSON-marshals the new unstructured, i.e. we JSON-marshal the unstructured object twice. Instead of having a separate utility function, we can take advantage of the `remarshal` function's marshaled copy of the unstructured to unmarshal and perform type-stripping.
I ran a 120s memory profile on an Intuit app controller. `remarshal` was responsible for 2% of the memory use. A 120s CPU profile showed `remarshal` as responsible for 3% of the CPU use. So I think the function is worth optimizing.
Testing with a medium-size manifest (about 100 lines) showed the following difference in …
=> chore: avoid unnecessary json marshal

pkg/diff/diff.go, pkg/diff/diff_test.go, pkg/utils/kube/resource_ops.go
Related to https://github.com/argoproj/argo-cd/issues/15693. 
This PR implements core logic from [argoproj/argo-cd#hide-annotations.md](https://github.com/argoproj/argo-cd/blob/master/docs/proposals/feature-bounties/hide-annotations.md) proposal to hide annotations on secret resources. 
This change will be integrated with Argo CD via https://github.com/argoproj/argo-cd/pull/18216. 
_Integration results:_
https://github.com/user-attachments/assets/f47d7b18-cfbc-4fef-8a63-cd7e670abcc7
=> feat: Add ability to hide certain annotations on secret resources

pkg/sync/common/types.go, pkg/sync/sync_context.go, pkg/sync/sync_context_test.go
Closes: https://github.com/argoproj/argo-cd/issues/20306
=> fix: Ability to disable Server Side Apply on individual resource level

.gitignore, .golangci.yaml, Dockerfile
I noticed the version difference between the go.mod and Dockerfile in the repo (1.17 vs 1.22).  Fixed a few other things also, like upgrading the version of the alpine/git image to the latest version.
- `FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)`
- -from alpine/git:v2.24.3 (4 years old) to alpine/git:v2.45.2
- `WARN [config_reader] The configuration option 'run.skip-files' is deprecated, please use 'issues.exclude-files'`
Test pass locally.  No new features really added so unsure if new tests are needed.
Do I need to run this against an argo-cd instance or with argo-cd test suite to ensure we're good?
=> chore(deps): upgrade go version in dockerfile

go.mod, go.sum, pkg/diff/diff.go, pkg/diff/diff_test.go, pkg/diff/testdata/data.go, pkg/diff/testdata/smd-deploy2-config.yaml, pkg/diff/testdata/smd-deploy2-live.yaml, pkg/diff/testdata/smd-deploy2-predicted-live.json, sonar-project.properties
Helps with https://github.com/argoproj/argo-cd/issues/20792
Removed and modified sets may only contain the fields that changed, not including key fields like "name". This can cause merge to fail, since it expects those fields to be present if they are present in the predicted live. Fortunately, structured merge diff folks have added an option to extracting items to add key fields, and we are going to use that.
Failure of the new test before the fix
```
Error:      	Received unexpected error:
error removing non config mutations for resource Deployment/nginx-deployment: error reverting webhook removed fields in predicted live resource: .spec.template.spec.containers: element 0: associative list with keys has an element that omits key field "name" (and doesn't have default value)
Test: …
```
=> fix: Server side diff now works correctly with some fields removal

.github/workflows/ci.yaml
Fixes issue that showed up in https://github.com/argoproj/gitops-engine/pull/650
[Error](https://github.com/argoproj/gitops-engine/actions/runs/12300709584/job/34329534904?pr=650#step:5:96)
=> fix: run go mod tidy in ci workflow

README.md
=> chore: update README get involved links

pkg/cache/cluster.go, pkg/cache/cluster_test.go, pkg/cache/mocks/ClusterCache.go, pkg/cache/settings.go, pkg/cache/settings_test.go
Problem statement is in https://github.com/argoproj/argo-cd/issues/8172#issuecomment-2277585238
The [IterateHierrchyV2](https://github.com/argoproj/gitops-engine/commit/6b2984ebc47085852a7b63a0fd0b73c52e986217) significantly improved performance, getting us ~90% of the way there. **But on huge clusters, we still have significant lock contention.**
The fix in this pull request approaches the problem differently - it avoids lock contention by utilizing a channel to process events from the cluster.
More details are in the comments.
=> fix: avoid resources lock contention utilizing channel

.golangci.yaml, pkg/cache/cluster_test.go, pkg/cache/predicates_test.go, pkg/diff/diff_test.go, pkg/sync/hook/helm/weight_test.go, pkg/sync/sync_context_test.go, pkg/utils/kube/kube_test.go
[testifylint](https://golangci-lint.run/usage/linters/#testifylint) checks usage of github.com/stretchr/testify and provides best practices recommandations
=> chore: enable testifylint linter

.github/workflows/ci.yaml
`~/go/pkg/mod` caching defined in actions/cache is a duplication of the default cache behavior of actions/setup-go.
This removes this duplication.
=> chore: remove actions/cache duplicated behavior with actions/setup-go

pkg/diff/diff_options.go, pkg/sync/sync_context.go, pkg/utils/kube/ctl.go, pkg/utils/kube/kubetest/mock_resource_operations.go, pkg/utils/kube/resource_ops.go
To make this fix available on 2.14, we should apply it to the release-2.14 branch.
argo-cd repo PR to test: https://github.com/argoproj/argo-cd/pull/22163
=> fix: New kube applier for server side diff dry run with refactoring (#662) (2.4 cherry-pick)

pkg/sync/sync_context.go
Fixes [ #21858](https://github.com/argoproj/argo-cd/issues/21858)
We did not properly check the correct dryRun flag before using ServerSideApply. We had previously checked only the sync context instead of passing the actual dryRun flag
During ArgoCD sync we always apply all resources in dry-run mode to make sure that all yamls are valid. In this case the
`sc.dryRun=False, dryRun=True`
Once we hit this case, we are essentially doing `kubectl apply --serverSide=true --dryRun=client` which leads to unintended results and actually wet applies resources: https://github.com/kubernetes/kubectl/blame/deef152435a8265c9cc91ff12e43c87132dbb0a8/pkg/cmd/apply/apply.go#L573
Following the bug reproduce steps:
Before fix:
Create application with resources across multiple sync waves (or hooks). I use a …
=> fix: Fix checking dryRun when using Server Side Apply

pkg/utils/kube/resource_ops.go
The info level apparently causes some spam, maybe related to the cache issues. Setting to effectively debug level (v1).
=> chore: Switch dry run applies to log with debug level

pkg/sync/common/types.go, pkg/sync/sync_context.go, pkg/sync/sync_context_test.go, pkg/utils/kube/kube.go, pkg/utils/kube/kube_test.go
Implementing the Gitops side of this issue: https://github.com/argoproj/argo-cd/issues/20896
Adds an api to `kube.go` to get the images from a resource. Adds those images to `ResourceSyncResult`. This API accounts for how different k8s resources define the images.
=> feat: return images from resources when sync occurs

go.mod
Getting error when executing `go list -modfile=~/go/src/github.com/argoproj/gitops-engine/go.mod -m -json -mod=mod all` locally it fails with 
Goland executing it in order to load dependencies list
=> fix: go list is not working due to k8s.io/externaljwt dependency

.github/workflows/ci.yaml, .golangci.yaml, agent/main.go, pkg/cache/cluster.go, pkg/cache/cluster_test.go, pkg/cache/resource.go, pkg/diff/diff_test.go, pkg/health/health_test.go, pkg/sync/sync_context.go, pkg/sync/sync_context_test.go, pkg/sync/sync_task_test.go, pkg/utils/json/json.go, pkg/utils/kube/kube.go, pkg/utils/kube/kube_test.go, pkg/utils/kube/resource_ops.go
I just ran the migrate tool and removed the `generated: lax` lines from .golangci.yaml (they didn't have any effect).
=> chore(deps): bump golangci-lint

pkg/diff/diff.go, pkg/diff/diff_test.go, pkg/diff/testdata/data.go, pkg/diff/testdata/ssd-svc-label-live.yaml, pkg/diff/testdata/ssd-svc-no-label-config.yaml, pkg/diff/testdata/ssd-svc-no-label-predicted-live.json
fixes https://github.com/argoproj/argo-cd/issues/23016 a bug that caused removed fields from predictedLive to be added back to predicted live resulting in removal of fields not showing in the diff
=> fix: Server-Side diff removed fields missing in diff

pkg/sync/sync_context.go, pkg/sync/sync_context_test.go
Replaces https://github.com/argoproj/gitops-engine/pull/708 reverted by https://github.com/argoproj/gitops-engine/pull/730
Fixes https://github.com/argoproj/argo-cd/issues/21788 
Tested in Argo CD by https://github.com/argoproj/argo-cd/pull/23304
=> fix(sync): create namespace before dry-run

pkg/utils/kube/resource_ops.go
The code is simple, but unit test framework is not setup to test the KubectlResourceOperation struct. 
This struct is mocked by the sync context tests.
The unit tests will come in another PR (https://github.com/argoproj/gitops-engine/pull/758), but we can ship this fix first.
=> fix: call validate on all options to prevent from errors

pkg/sync/sync_context_test.go, pkg/sync/sync_task.go
Fixes https://github.com/argoproj/argo-cd/issues/24242
The root cause of the issue is, when the `resourceKey` is calculated from the object associated with`syncTask`, it is calculated from the desired object instead of the live object. In the desired object, the `resourceKey` will be filled in with the destination namespace configured in the Application even for cluster scoped resource, where the namespace must be   empty.
For fixing the issue, when the `syncTask` contains a `liveObj`, calculate the `resourceKey` using the live object instead of the desired object set in the `syncTask`. This desired object contains the application destination namespace even for cluster scoped resources.
=> fix(sync): ApplyOutOfSyncOnly=true sync option is not honoured for cluster scoped resources
